services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fx_trading_api
    ports:
      - '8000:8000'
    env_file:
      - .env.production
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    container_name: fx_trading_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
