services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fx_trading_api
    volumes:
      - .:/app
      - /app/dist
    ports:
      - '8000:8000'
    env_file:
      - .env.production
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    container_name: fx_trading_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'fx_trading_user'
      POSTGRES_PASSWORD: 'fx_trading_pass'
      POSTGRES_DB: 'fx_trading_db'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
